### ISSUE TITLE
Error: Second argument to Lang.bind() must be a function, not undefined

### ISSUE THREAD

**Issue by vasekp** [kleingeist/alternate-tab-above#1]
After an update today (I'm not updating regularly, though), I am getting the error quoted in the title in the Looking Glass. My system has a `$LANG = cs_CZ.UTF-8` if that is relevant.

**Comment by kleingeist** [comment]
Hi Vasekp,
thanks for your report. The error occurs due to changes in the gnome-shell API. I followed the latest changes which did introduce some changes.

Which version of gnome-shell do us use? (`gnome-shell --version`)
I will try if it is possible to upload different packages for the different versions of gnome-shell to https://extensions.gnome.org/extension/968/alternatetababove/

**Comment by kleingeist** [comment]
i just introduced tags to the repo.
you can now download the release matching your gnome-shell version from github if downgrading via extensions.gnome.org does not work
1. Download the package from 
   https://github.com/kleingeist/alternate-tab-above/releases
2. Extract it to 
   `$HOME/.local/share/gnome-shell/extensions`
3. And rename the extracted folder `alternate-tab-above-$version` to `$HOME/.local/share/gnome-shell/extensions/`
